trigger:
- master

pool: miMaquina

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test-ci
    npm run build
  displayName: 'npm install, test and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarCloud'
    organization: 'diegosgil'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1
  displayName: 'run SonarCloud'
  
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

